name: Android CI

# 언제 실행할 것인가?
on:
  push:
    branches: [ "main" ] # main에 푸시될 때
  pull_request:
    branches: [ "main" ] # main으로 PR이 올라올 때

jobs:
  build:
    runs-on: ubuntu-latest # 리눅스 환경에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 내 코드를 서버로 가져옴

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle # 빌드 속도를 위해 캐시 사용

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # 실행 권한 부여

      # 1. 린트 검사 (스타일 체크)
      - name: Run Lint
        run: ./gradlew lintDebug

      # 2. 로컬 단위 테스트 실행
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # 3. 앱 빌드 (에러가 없는지 확인용)
      - name: Build debug APK
        run: ./gradlew assembleDebug